# Generated by Django 3.0.5 on 2020-04-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='how_heard',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='where',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
