# Generated by Django 3.0.5 on 2020-04-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200410_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='how_heard',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='where',
            field=models.CharField(default='', max_length=100),
        ),
    ]
