# Generated by Django 3.0.3 on 2020-04-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200415_1419'),
        ('main_app', '0009_auto_20200415_1429'),
    ]

    operations = [
    ]
