# Generated by Django 3.0.5 on 2020-04-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20200415_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='quote',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
