# Generated by Django 3.0.5 on 2020-04-17 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile'),
        ),
    ]
