# Generated by Django 3.0.5 on 2020-04-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20200417_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='profile_photo_url',
            field=models.CharField(default='', max_length=200, verbose_name='Profile photo'),
        ),
    ]
