# Generated by Django 3.0.5 on 2020-04-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20200417_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fave_movie',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Favourite movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo_url',
            field=models.CharField(default='', max_length=200, verbose_name='Profile photo URL'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
