# Generated by Django 3.0.5 on 2020-04-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200413_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fave_movie',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Favourite Movie'),
        ),
    ]
