# Generated by Django 3.0.5 on 2020-04-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200415_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='recommend',
            field=models.BooleanField(),
        ),
    ]
